sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install -g yaspeller
  - npm install -g spellchecker-cli
  - npm install -g markdown-link-check
  # generate dictionary in JSON format
  - awk '{printf("%s\0", $0)}' .spelling | jq -csR 'split("\u0000")' > .yaspeller-dictionary.json
script:
  - yaspeller --dictionary .yaspeller-dictionary.json -e ".md" ./
  - spellchecker --language=en-US --plugins spell repeated-words syntax-mentions syntax-urls --ignore "[A-Zx0-9./_-]+" "[u0-9a-fA-F]+" "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z" "[0-9dhms:-]+" "(metric|entity|tag|[emtv])[:0-9]*" --dictionary=.spelling --files '**/*.md'
  - find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
