sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install -g yaspeller
  - npm install -g markdown-link-check
script: 
  - yaspeller -e ".md" ./
  - find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
