sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install --global --production yaspeller spellchecker-cli markdown-link-check
  - source .travis-functions.sh
  - generate_yaspeller_dictionary .spelling
script:
  - print_modified_files
  - spellcheck
  - linkcheck
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
