sudo: false
language: node_js
node_js:
  - "8"
install:
  - source .travis-functions.sh
  - install_checkers
script:
  - print_modified_markdown_files
  - spellcheck
  - linkcheck
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
