sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install --global --production yaspeller spellchecker-cli markdown-link-check
  # generate dictionary in JSON format
  - awk '{$1=$1};1' .spelling | jq -csR 'split("\n")' > .yaspeller-dictionary.json
script:
  - yaspeller --max-requests=10 --dictionary .yaspeller-dictionary.json -e ".md" ./
  - bash list_modified_md_files.sh | xargs -d '\n' -n1 spellchecker --language=en-US --plugins spell repeated-words syntax-mentions syntax-urls --ignore "[A-Zx0-9./_-]+" "[u0-9a-fA-F]+" "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z" "[0-9dhms:-]+" "(metric|entity|tag|[emtv])[:0-9]*" --dictionary=.spelling --files {}
  - bash list_modified_md_files.sh | xargs -d '\n' -n1 markdown-link-check
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
